apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
  labels:
    app: feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
      - name: feed
        image: cocorine/udagram-api-feed:v0
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-pg-secrets
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: aws-credentials
      volumes:
        - name: aws-credentials
          configMap:
            name: aws-credentials
