# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and push docker images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag reverseproxy cocorine/reverseproxy:v0
    - run: docker tag udagram-api-user cocorine/udagram-api-user:v0
    - run: docker tag udagram-api-feed cocorine/udagram-api-feed:v0
    - run: docker tag udagram-frontend:local cocorine/udagram-frontend:v1
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker push cocorine/reverseproxy:v0
    - run: docker push cocorine/udagram-api-user:v0
    - run: docker push cocorine/udagram-api-feed:v0
    - run: docker push cocorine/udagram-frontend:v1
